### ISSUE TITLE
jamovi_librdata not handling TIMESTAMP values

### ISSUE THREAD

**Issue by ofajardo** [jamovi/jamovi-readstat#1]
Just a suggestion:

currently jamovi_librdata does not return values of type RDATA_TYPE_TIMESTAMP. It is easy to handle them, basically just do the same as REAL, it will then return a unix epoch that the user can handle himself.
In librdata.pyx:

```
        if type == rdata_type_t.RDATA_TYPE_REAL or type == rdata_type_t.RDATA_TYPE_TIMESTAMP:
            array = np.empty([count], dtype=np.float64)
            for i in range(count):
                array[i] = doubles[i];
```
It seems that in R the timestamps have time zone info, but I think librdata does not return that information. So, there is a source of errors there, but that's an issue in librdata itself.

**Comment by jonathon-love** [comment]
ah! thanks.

**Comment by ofajardo** [comment]
Today I have written a parser using your librdata.pyx to tranlate to pandas dataframes. Once I have sorted out a few details, I am planning to put the code in my personal github in a new project.
Are you OK with that? Besides stating clearly in the README that I am using your library, would you like anything else, like me commiting your pyx and pyd with your name? (again I will avoid git submodules)

**Comment by jonathon-love** [comment]
yeah, commit with my name, etc. but what license are you wanting to use?

jonathon

**Comment by ofajardo** [comment]
Oh good question, I haven't tought about it ... Same as jamovi maybe? I am open ... What's your suggestion? Do you have any concerns?

**Comment by jonathon-love** [comment]
i'm a conservative, so i go AGPL, and if someone wants to use it in something proprietary, well they can come talk to me (so not that conservative, apparently).

but there's a case for something using something liberal.

**Comment by ofajardo** [comment]
I would do it from my personal time for fun and with the hope of helping the community. I have no intention to make any profit out of it, and would prefer than others cannot make profit, but they can use if it is open for the community. 
In that sense AGPL sounds good. But again I'm open. I also have to inherit the licenses from jamovi and librdata, I think.
This project I would do during Xmas break, so no related to work, and therefore would host on my personal github and not my company's as I had to do with pyreadstat as I did it during working hours.
Does all of this fit with your own ideas? Or any concerns?

**Comment by jonathon-love** [comment]
yup, sounds good. let's go AGPL then.

**Comment by ofajardo** [comment]
OK, first version here: https://github.com/ofajardo/pyreadr/

**Comment by jonathon-love** [comment]
cool. i've actually improved the .pxd's (added write support for example):

https://github.com/jamovi/jamovi-readstat/blob/master/jamovi/librdata.pxd
https://github.com/jamovi/jamovi-readstat/blob/master/jamovi/readstat.pxd

jonathon

**Comment by ofajardo** [comment]
Great! Thanks a lot. 

Btw, I have introduced one more change I needed to librdata pyx. I have not submitted a PR assuming you need stability for jamovi, but I can do if you like. Otherwise I just maintain the changes on my side.

**Comment by jonathon-love** [comment]
oh, what changes?

**Comment by ofajardo** [comment]
The first one I mentioned in this issue. Second the ability to parse only the table and column names and skip the rest. This is to explore quickly the content of the file without parsing everything, or to parse only selected tables.

They are here:

https://github.com/ofajardo/pyreadr/commit/4506242398e938f7c6c9ef7cee3b22b5ac9009d5

**Comment by ofajardo** [comment]
Just saw that the timestamp thing is in jamovi already. Thanks for that. I'll check the writing support.
