### ISSUE TITLE
reading with R RData and Rds files written by jamovi-readstat librdata fails

### ISSUE THREAD

**Issue by ofajardo** [jamovi/jamovi-readstat#3]
I produced two files "write_test.RData" and "write_test.Rds". The writing was completed without errors. But when trying to open them in R the following error arise:

```r
> load("write_test.RData")
Error in load("write_test.RData") : 
  value of 'SET_ATTRIB' must be a pairlist or NULL, not a 'double'
> readRDS("write_test.Rds")
Error in readRDS("write_test.Rds") : 
  value of 'SET_ATTRIB' must be a pairlist or NULL, not a 'double'
```

I tried the readEX.c file from librdata and the RData and Rds files produced by that program are readable in R.

here my python code to generate the files, am I missing something?

```python
from jamovi import librdata

writer = librdata.Writer()

writer.open("write_test.Rds", "rds")
#writer.open("write_test.RData", "rdata")

writer.set_row_count(2)
writer.add_column("mystr", str)
writer.insert_value(0,0, "a")
writer.insert_value(1,0, "b")

writer.add_column("mynum", float)
writer.insert_value(0,1, 1.1)
writer.insert_value(1,1, 2.2)

writer.close()
```
files attached just in case
[write_examples.tar.gz](https://github.com/jamovi/jamovi-readstat/files/2717182/write_examples.tar.gz)

In addition, notice that RData files may contain multiple tables each with it's own name (while Rds supports one single table with no name). Right now it seems to me you are supporting a single table, it would be nice if you could support multiple tables.

Also: it would be nice to add support for types LOGICAL and TIMESTAMP. For logical the user could pass an integer column, for TIMESTAMP a float with the UTC timestamp. I also did not understand if a levels column can be supplied? I see a method to do with the Column class ... how to use it?

Finally: the unittest in jamovi-readstat are failing in my hands:

```
otto@ubuntu:~/Documents/gitrepos/jamovi-readstat$ python -m unittest discover
Segmentation fault (core dumped)
```

**Comment by ofajardo** [comment]
I also tested the similar data as writeEx, in that case the error in R is a bit different:

```
> load("write_test.RData")
Error in load("write_test.RData") : 
  ReadItem: unknown type 0, perhaps written by later version of R

```

and the python code:

```python
rom jamovi import librdata
writer = librdata.Writer()

#writer.open("write_test.Rds", "rds")
writer.open("write_test.RData", "rdata")


#writer.set_row_count(2)
writer.add_column("column1", float)
writer.insert_value(0,0, 0.0)
writer.insert_value(1,0, 100.0)

writer.add_column("column2", str)
writer.insert_value(0,1, "hello")
writer.insert_value(1,1, "goodbye")

writer.close()
```

**Comment by jonathon-love** [comment]
hmm, i'll have a gander.

> In addition, notice that RData files may contain multiple tables each with it's own name (while Rds supports one single table with no name). Right now it seems to me you are supporting a single table, it would be nice if you could support multiple tables.
>
> Also: it would be nice to add support for types LOGICAL and TIMESTAMP. For logical the user could pass an integer column, for TIMESTAMP a float with the UTC timestamp.

sooo, i originally had the plan to develop generally useful libraries that i could send to pypi, but two things happened. 1) evan wouldn't accept my changes without unit-testing, which meant rewriting the whole build system 2) you released your libraries. :)

since then, there hasn't been the motivation to make them general purpose, and so i've cut corners and made them more jamovi-centric.

so the features you describe are nice, but people are probably better off just using your libraries. :)

>  I also did not understand if a levels column can be supplied? I see a method to do with the Column class ... how to use it?

this is how i use it in jamovi:

https://github.com/jamovi/jamovi/blob/master/server/jamovi/server/formatio/rdata.py#L29-L83

```
column.add_level_labels(labels)
```

you just provide it with a list (or iterable object) of strings

jonathon

**Comment by ofajardo** [comment]
> hmm, i'll have a gander.

Thanks!

> so the features you describe are nice, but people are probably better off just using your libraries. :)

Absolutely fair! I'll implement these features on my side.

**Comment by jonathon-love** [comment]
> here my python code to generate the files, am I missing something?

it wasn't completely clear to me, but i got the impression from librdata that you had to add all the columns before writing *to* them - so i maintained those expectations when writing the library.

of course, this may not be a limitation of librdata, in which case i can rejig `jamovi.librdata`, but i'm not sure. if it is a limitation, i should add an informative error message :)

**Comment by jonathon-love** [comment]
but if you just want to get your code working, change:

```
writer.add_column("mystr", str)
writer.insert_value(0,0, "a")
writer.insert_value(1,0, "b")

writer.add_column("mynum", float)
writer.insert_value(0,1, 1.1)
writer.insert_value(1,1, 2.2)
```

to:

```
writer.add_column("mystr", str)
writer.add_column("mynum", float)

writer.insert_value(0,0, "a")
writer.insert_value(1,0, "b")
writer.insert_value(0,1, 1.1)
writer.insert_value(1,1, 2.2)
```

**Comment by ofajardo** [comment]
Yeah actually as writeEx in librdata does add all columns first I also tried that before.
 To be sure I cloned again and rebuild from scratch and tried as you suggested. I still get the same error.
Is my problem reproducible? Or everything is good for you?

Notice that the error arises in R when trying to load the .RData file. There is no error on the python side.

**Comment by ofajardo** [comment]
Sorry, I don't know how I have been testing so far, but now it is working ...
sorry for bugging!

**Comment by ofajardo** [comment]
Probably this sounds weird, but this is what I think was happening:

I got the issue as described. Unittest were also failing.

Then I installed jamovi (GUI) to see if the issue was also there. There was no issue.

Then I tested again writing and all was fine. Also unittesting now works. 

I admit that I could have done the writing RData test wrong a few times, but it looks a bit unlikely that I run the unnittest wrong before ...

It looks as if there was something that came with jamovi installation that is necessary. 

Any idea or suggestion? 

Now even if I uninstalled flatpak I don't get the error anymore. I'll try to test on another naive machine next week.

**Comment by ofajardo** [comment]
Just tested on windows and looks OK.

What I mentioned before I tested on a fresh installation of Lubuntu. It happened to me in the past that some basic libraries (zlib I think ) were missing. Maybe that's the case that something was missing.

**Comment by jonathon-love** [comment]
oh yeah! zlib sounds like a likely culprit!

thanks for your efforts here :)
